### ISSUE TITLE
Get Activity History

### ISSUE THREAD

**Issue by jecolvin** [yergi/DestinyAPI#9]
Relevant API call is [GetActivityHistory](http://bungienetplatform.wikia.com/wiki/GetActivityHistory)

Requires destinyMembershipId, membershipType, and characterId.

Accepts a parameter for game mode type. Value to return trials is `?modes=14`.

**Comment by jecolvin** [comment]
Since this returns a timestamp for the activity, I'm thinking we could use a datediff based on the most recent Trials round to determine a card, no?

**Comment by johnofmars** [comment]
Most recent is a good start, but specifying a final game of card is needed for historical analysis. When specifying a final card, there are several options for determining the rest of the games in the card:
1. Either # of wins (with/without boons) or 
2. finding all games with the same teammates
3. Having user manually specifying first game

**Comment by jecolvin** [comment]
That's not very user friendly though. GetActivityHistory returns a time stamp for each activity, so could we have people provide the date they played trials and get the final card by finding the highest time stamp within the date provided?

**Comment by rmcentyre** [comment]
Trials runs are always contiguous. An easy way to start would be to fetch the last n activities for a given game type, with an optional parameter to start at an arbitrary activity id. To avoid unintentional fence-posting by the user, we name the integer parameter n something like "games_played".

**Comment by rmcentyre** [comment]
This is probably done, please validate and close.

**Comment by jecolvin** [comment]
Validated and closed.
